version: '3.5'
services:
  web:
    image: "quant_trading:latest" 
    build: .
    command: python3 quant_trading/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
