version: '3.5'
services:
  db:
    image: mariadb:latest 
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3308:3306"
  app:
    image: "quant_trading:latest" 
    build: .
    command: python3 quant_trading/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "3000:3000"
    depends_on:
      - db

volumes:
  mariadb_data: