# Generated by Django 5.0.2 on 2024-03-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='date',
            field=models.IntegerField(unique=True),
        ),
    ]
