# Generated by Django 5.0.2 on 2024-03-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_images_simulations_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulations',
            name='strategy',
            field=models.CharField(default='', max_length=100),
        ),
    ]
