# Generated by Django 5.0.2 on 2024-03-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='date',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='stocks',
            unique_together={('date', 'type')},
        ),
    ]
