# Generated by Django 5.0.2 on 2024-03-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_stocks_date_alter_stocks_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
